apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadsick9385-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadsick9385-tenant-component
    app.kubernetes.io/part-of: loadsick9385-tenant-app
  name: loadsick9385-tenant-component
  namespace: loadsick9385-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadsick9385-tenant-component
    weight: null
status: {}
